cd /d "%~dp0
del Architecture\Floor_400x400.uasset
del Architecture\Pillar_50x500.uasset
del Architecture\SM_AssetPlatform.uasset
del Architecture\Wall_400x200.uasset
del Architecture\Wall_400x300.uasset
del Architecture\Wall_400x400.uasset
del Architecture\Wall_500x500.uasset
del Architecture\Wall_Door_400x300.uasset
del Architecture\Wall_Door_400x400.uasset
del Architecture\Wall_Window_400x300.uasset
del Architecture\Wall_Window_400x400.uasset
del Audio\Collapse01.uasset
del Audio\Collapse02.uasset
del Audio\Collapse_Cue.uasset
del Audio\Explosion01.uasset
del Audio\Explosion02.uasset
del Audio\Explosion_Cue.uasset
del Audio\Fire01.uasset
del Audio\Fire01_Cue.uasset
del Audio\Fire_Sparks01.uasset
del Audio\Fire_Sparks01_Cue.uasset
del Audio\Light01.uasset
del Audio\Light01_Cue.uasset
del Audio\Light02.uasset
del Audio\Light02_Cue.uasset
del Audio\Smoke01.uasset
del Audio\Smoke01_Cue.uasset
del Audio\Starter_Background_Cue.uasset
del Audio\Starter_Birds01.uasset
del Audio\Starter_Music01.uasset
del Audio\Starter_Music_Cue.uasset
del Audio\Starter_Wind05.uasset
del Audio\Starter_Wind06.uasset
del Audio\Steam01.uasset
del Audio\Steam01_Cue.uasset
del Blueprints\Blueprint_CeilingLight.uasset
del Blueprints\Blueprint_Effect_Explosion.uasset
del Blueprints\Blueprint_Effect_Fire.uasset
del Blueprints\Blueprint_Effect_Smoke.uasset
del Blueprints\Blueprint_Effect_Sparks.uasset
del Blueprints\Blueprint_Effect_Steam.uasset
del Blueprints\Blueprint_WallSconce.uasset
del Blueprints\BP_LightStudio.uasset
del Blueprints\Assets\FogBrightnessLUT.uasset
del Blueprints\Assets\M_LightStage_Arrows.uasset
del Blueprints\Assets\M_LightStage_Skybox_Black.uasset
del Blueprints\Assets\M_LightStage_Skybox_HDRI.uasset
del Blueprints\Assets\M_LightStage_Skybox_Master.uasset
del Blueprints\Assets\Skybox.uasset
del Blueprints\Assets\SM_Arrows.uasset
del Blueprints\Assets\SunlightColorLUT.uasset
rmdir Blueprints\Assets
del HDRI\HDRI_Epic_Courtyard_Daylight.uasset
del Maps\Advanced_Lighting.umap
del Maps\Advanced_Lighting_BuiltData.uasset
del Maps\Minimal_Default.umap
del Maps\Minimal_Default_BuiltData.uasset
del Maps\StarterMap.umap
del Maps\StarterMap_BuiltData.uasset
del Materials\M_AssetPlatform.uasset
del Materials\M_Basic_Floor.uasset
del Materials\M_Basic_Wall.uasset
del Materials\M_Brick_Clay_New.uasset
del Materials\M_Brick_Clay_Old.uasset
del Materials\M_Brick_Cut_Stone.uasset
del Materials\M_Brick_Hewn_Stone.uasset
del Materials\M_Ceramic_Tile_Checker.uasset
del Materials\M_CobbleStone_Pebble.uasset
del Materials\M_CobbleStone_Rough.uasset
del Materials\M_CobbleStone_Smooth.uasset
del Materials\M_ColorGrid_LowSpec.uasset
del Materials\M_Concrete_Grime.uasset
del Materials\M_Concrete_Panels.uasset
del Materials\M_Concrete_Poured.uasset
del Materials\M_Concrete_Tiles.uasset
del Materials\M_Glass.uasset
del Materials\M_Ground_Grass.uasset
del Materials\M_Ground_Gravel.uasset
del Materials\M_Ground_Moss.uasset
del Materials\M_Metal_Brushed_Nickel.uasset
del Materials\M_Metal_Chrome.uasset
del Materials\M_Metal_Copper.uasset
del Materials\M_Metal_Gold.uasset
del Materials\M_Metal_Rust.uasset
del Materials\M_Metal_Steel.uasset
del Materials\M_Rock_Basalt.uasset
del Materials\M_Rock_Marble_Polished.uasset
del Materials\M_Rock_Sandstone.uasset
del Materials\M_Rock_Slate.uasset
del Materials\M_Tech_Checker_Dot.uasset
del Materials\M_Tech_Hex_Tile.uasset
del Materials\M_Tech_Hex_Tile_Pulse.uasset
del Materials\M_Tech_Panel.uasset
del Materials\M_Water_Lake.uasset
del Materials\M_Water_Ocean.uasset
del Materials\M_Wood_Floor_Walnut_Polished.uasset
del Materials\M_Wood_Floor_Walnut_Worn.uasset
del Materials\M_Wood_Oak.uasset
del Materials\M_Wood_Pine.uasset
del Materials\M_Wood_Walnut.uasset
del Particles\P_Ambient_Dust.uasset
del Particles\P_Explosion.uasset
del Particles\P_Fire.uasset
del Particles\P_Smoke.uasset
del Particles\P_Sparks.uasset
del Particles\P_Steam_Lit.uasset
del Particles\Materials\M_Burst.uasset
del Particles\Materials\M_Dust_Particle.uasset
del Particles\Materials\M_explosion_subUV.uasset
del Particles\Materials\M_Fire_SubUV.uasset
del Particles\Materials\m_flare_01.uasset
del Particles\Materials\M_Heat_Distortion.uasset
del Particles\Materials\M_Radial_Gradient.uasset
del Particles\Materials\M_radial_ramp.uasset
del Particles\Materials\M_smoke_subUV.uasset
del Particles\Materials\M_Spark.uasset
rmdir Particles\Materials
del Props\MaterialSphere.uasset
del Props\SM_Bush.uasset
del Props\SM_Chair.uasset
del Props\SM_CornerFrame.uasset
del Props\SM_Couch.uasset
del Props\SM_Door.uasset
del Props\SM_DoorFrame.uasset
del Props\SM_GlassWindow.uasset
del Props\SM_Lamp_Ceiling.uasset
del Props\SM_Lamp_Wall.uasset
del Props\SM_MatPreviewMesh_02.uasset
del Props\SM_PillarFrame.uasset
del Props\SM_PillarFrame300.uasset
del Props\SM_Rock.uasset
del Props\SM_Shelf.uasset
del Props\SM_Stairs.uasset
del Props\SM_Statue.uasset
del Props\SM_TableRound.uasset
del Props\SM_WindowFrame.uasset
del Props\Materials\M_Bush.uasset
del Props\Materials\M_Chair.uasset
del Props\Materials\M_Door.uasset
del Props\Materials\M_Frame.uasset
del Props\Materials\M_Lamp.uasset
del Props\Materials\M_MaterialSphere.uasset
del Props\Materials\M_MaterialSphere_Plain.uasset
del Props\Materials\M_Rock.uasset
del Props\Materials\M_Shelf.uasset
del Props\Materials\M_Statue.uasset
del Props\Materials\M_StatueGlass.uasset
del Props\Materials\M_TableRound.uasset
rmdir Props\Materials
del Shapes\Shape_Cone.uasset
del Shapes\Shape_Cube.uasset
del Shapes\Shape_Cylinder.uasset
del Shapes\Shape_NarrowCapsule.uasset
del Shapes\Shape_Pipe.uasset
del Shapes\Shape_Pipe_180.uasset
del Shapes\Shape_Pipe_90.uasset
del Shapes\Shape_Plane.uasset
del Shapes\Shape_QuadPyramid.uasset
del Shapes\Shape_Sphere.uasset
del Shapes\Shape_Torus.uasset
del Shapes\Shape_Trim.uasset
del Shapes\Shape_Trim_90_In.uasset
del Shapes\Shape_Trim_90_Out.uasset
del Shapes\Shape_TriPyramid.uasset
del Shapes\Shape_Tube.uasset
del Shapes\Shape_Wedge_A.uasset
del Shapes\Shape_Wedge_B.uasset
del Shapes\Shape_WideCapsule.uasset
del Textures\T_Brick_Clay_New_D.uasset
del Textures\T_Brick_Clay_New_M.uasset
del Textures\T_Brick_Clay_New_N.uasset
del Textures\T_Brick_Clay_Old_D.uasset
del Textures\T_Brick_Clay_Old_N.uasset
del Textures\T_Brick_Cut_Stone_D.uasset
del Textures\T_Brick_Cut_Stone_N.uasset
del Textures\T_Brick_Hewn_Stone_D.uasset
del Textures\T_Brick_Hewn_Stone_M.uasset
del Textures\T_Brick_Hewn_Stone_N.uasset
del Textures\T_Burst_M.uasset
del Textures\T_Bush_D.uasset
del Textures\T_Bush_N.uasset
del Textures\T_Ceramic_Tile_M.uasset
del Textures\T_Ceramic_Tile_N.uasset
del Textures\T_Chair_M.uasset
del Textures\T_Chair_N.uasset
del Textures\T_Checker_Noise_M.uasset
del Textures\T_CobbleStone_Pebble_D.uasset
del Textures\T_CobbleStone_Pebble_M.uasset
del Textures\T_CobbleStone_Pebble_N.uasset
del Textures\T_CobbleStone_Rough_D.uasset
del Textures\T_CobbleStone_Rough_N.uasset
del Textures\T_CobbleStone_Smooth_D.uasset
del Textures\T_CobbleStone_Smooth_M.uasset
del Textures\T_CobbleStone_Smooth_N.uasset
del Textures\T_Concrete_Grime_D.uasset
del Textures\T_Concrete_Panels_D.uasset
del Textures\T_Concrete_Panels_N.uasset
del Textures\T_Concrete_Poured_D.uasset
del Textures\T_Concrete_Poured_N.uasset
del Textures\T_Concrete_Tiles_D.uasset
del Textures\T_Concrete_Tiles_M.uasset
del Textures\T_Concrete_Tiles_N.uasset
del Textures\T_Concrete_Tiles_Variation_M.uasset
del Textures\T_Detail_Rocky_N.uasset
del Textures\T_Door_M.uasset
del Textures\T_Door_N.uasset
del Textures\T_Dust_Particle_D.uasset
del Textures\T_Explosion_SubUV.uasset
del Textures\T_Fire_SubUV.uasset
del Textures\T_Fire_Tiled_D.uasset
del Textures\T_Frame_M.uasset
del Textures\T_Frame_N.uasset
del Textures\T_Gradinet_01.uasset
del Textures\T_Ground_Grass_D.uasset
del Textures\T_Ground_Grass_N.uasset
del Textures\T_Ground_Gravel_D.uasset
del Textures\T_Ground_Gravel_N.uasset
del Textures\T_ground_Moss_D.uasset
del Textures\T_Ground_Moss_N.uasset
del Textures\T_Lamp_M.uasset
del Textures\T_Lamp_N.uasset
del Textures\T_Metal_Copper_D.uasset
del Textures\T_Metal_Gold_D.uasset
del Textures\T_Metal_Rust_D.uasset
del Textures\T_Metal_Rust_N.uasset
del Textures\T_Metal_Steel_D.uasset
del Textures\T_Metal_Steel_N.uasset
del Textures\T_Perlin_Noise_M.uasset
del Textures\T_RockMesh_M.uasset
del Textures\T_RockMesh_N.uasset
del Textures\T_Rock_Basalt_D.uasset
del Textures\T_Rock_Basalt_N.uasset
del Textures\T_Rock_Marble_Polished_D.uasset
del Textures\T_Rock_Sandstone_D.uasset
del Textures\T_Rock_Sandstone_N.uasset
del Textures\T_Rock_Slate_D.uasset
del Textures\T_Rock_Slate_N.uasset
del Textures\T_Rock_Smooth_Granite_D.uasset
del Textures\T_Shelf_M.uasset
del Textures\T_Shelf_N.uasset
del Textures\T_Single_Tile_N.uasset
del Textures\T_Smoke_SubUV.uasset
del Textures\T_Smoke_Tiled_D.uasset
del Textures\T_Spark_Core.uasset
del Textures\T_Statue_M.uasset
del Textures\T_Statue_N.uasset
del Textures\T_TableRound_M.uasset
del Textures\T_TableRound_N.uasset
del Textures\T_Tech_Dot_M.uasset
del Textures\T_Tech_Dot_N.uasset
del Textures\T_Tech_Hex_Tile_M.uasset
del Textures\T_Tech_Hex_Tile_N.uasset
del Textures\T_Tech_Panel_M.uasset
del Textures\T_Tech_Panel_N.uasset
del Textures\T_Water_M.uasset
del Textures\T_Water_N.uasset
del Textures\T_Wood_Floor_Walnut_D.uasset
del Textures\T_Wood_Floor_Walnut_M.uasset
del Textures\T_Wood_Floor_Walnut_N.uasset
del Textures\T_Wood_Oak_D.uasset
del Textures\T_Wood_Oak_N.uasset
del Textures\T_Wood_Pine_D.uasset
del Textures\T_Wood_Pine_N.uasset
del Textures\T_Wood_Walnut_D.uasset
del Textures\T_Wood_Walnut_N.uasset
rmdir Architecture
rmdir Audio
rmdir Blueprints
rmdir HDRI
rmdir Maps
rmdir Materials
rmdir Particles
rmdir Props
rmdir Shapes
rmdir Textures